# Generated by Django 6.0.1 on 2026-01-22 18:26

import users.models.photos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userphoto_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_preference',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('A', 'All')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(upload_to=users.models.photos.get_file_path),
        ),
    ]
